[colors.primary]
background = "#000000"
# foreground = "#BFBDB6"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#39BAE6"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#95E6CB"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#7FD962"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#39BAE6"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#FFB454"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#6C5980"

[colors.normal]
black = "#000000"
red = "#D95757"
green = "#7FD962"
yellow = "#FFB454"
blue = "#39BAE6"
magenta = "#6C5980"
cyan = "#95E6CB"
white = "#FFFFFF"

[colors.bright]
black = "#475266"
red = "#F07178"
green = "#AAD94C"
yellow = "#E6B673"
blue = "#59C2FF"
magenta = "#D2A6FF"
cyan = "#C7FFFC"
white = "#FAFAFA"
